# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: api-default-deny-ingress
  namespace: backend
spec:
  endpointSelector:
    matchLabels:
      app: api
  ingress:
    - {}
